### PR TITLE
iRODS upgrade for autoqc

### PR DESCRIPTION
**Pull request by iainrb**
- Use perl-irods-wrap for iRODS operations in autoqc
- Remove old iRODS.pm module
- Configure Travis to use iRODS

### CODE REVIEW

**Comment by keithj** [comment]
I've factored out some iRODS installation scripts into https://github.com/wtsi-npg/disposable-irods and there is a distribution tarball containing the scripts at https://github.com/wtsi-npg/disposable-irods/releases/download/1.0/disposable-irods-1.0.tar.gz (which saves cloning the repository).

**Comment by dkj** [comment]
Hi Iain, can you try updating (and so hopefully trimming) this to use the new [disposable-irods](/wtsi-npg/disposable-irods) (and rebase, maybe squash)? David

**Comment by keithj** [comment]
This will be needed for the next release. The switch to [wtsi-npg/disposable-irods](https://github.com/wtsi-npg/disposable-irods) will provide support for tests against iRODS 4.1.10

**Comment by iainrb** [comment]
Superseded by https://github.com/wtsi-npg/npg_qc/pull/388

**Pull request closed without merging**
