### PR TITLE
Dev mqc temp qc status

### PR DESCRIPTION
**Pull request by jmtcsngr**
Database changes/initial models for new status in mqc.

### CODE REVIEW

**Comment by jenniferliddle** [comment]
It isn't clear to me what the purpose of 'mqc_outcome_hist' is, since it appears to contain exactly the same information as 'mqc_outcome_ent'.

**Comment by jmtcsngr** [comment]
The idea was to track every change in the entity table. Whenever I 
update the entity table I will also add a row in the historic. At any 
time they should show the same status but the historic will also have 
all previous status.

On 04/02/15 09:11, Jennifer Liddle wrote:
>
> It isn't clear to me what the purpose of 'mqc_outcome_hist' is, since 
> it appears to contain exactly the same information as 'mqc_outcome_ent'.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/wtsi-npg/npg_qc/pull/70#issuecomment-72816997>.
>


-- 
Jaime M. Tovar Corona
Senior Software Developer
Sequence Informatics
Wellcome Trust Sanger Institute
Wellcome Trust Genome Campus
Hinxton
Cambridge UK
CB10 1SA

Email: jmtc@sanger.ac.uk
Tel:   +44 (0)1223 834244 ext.8306




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by jenniferliddle** [comment]
Tracking changes is a Good Thing!
In this case I'm not sure of the need for a separate table to track changes. Surely we could read the current data from the history table by selecting the record with the latest 'modified' date, or probably better, by having an 'iscurrent' flag. That way we remove the need to have two tables, and having to have code to keep them in sync. And it means you only need one write to one table, instead of two writes to two tables.

**Comment by jmtcsngr** [comment]
Having one table saves time to insert, but is may be more expensive in 
the select. In the entity we can hit the table using the primary keys to 
get data. If we want to do a select to get the last historic we will 
need an extra index for timestamp or iscurrent, otherwise it will get 
progressively slower as the table grows.

Also it allows less work when maintaining the tables. For example you 
can dump big chunks of old history to free space without worrying about 
altering what is in the entity table. It kind of keeps business rules 
out of the tables. On the other hand it adds time for development if we 
need to change things you are absolutely right about it.

Because I think we will be selecting to display data more often than 
inserting I think it may be worth to use two tables. What you think?

On 04/02/15 10:00, Jennifer Liddle wrote:
>
> Tracking changes is a Good Thing!
> In this case I'm not sure of the need for a separate table to track 
> changes. Surely we could read the current data from the history table 
> by selecting the record with the latest 'modified' date, or probably 
> better, by having an 'iscurrent' flag. That way we remove the need to 
> have two tables, and having to have code to keep them in sync. And it 
> means you only need one write to one table, instead of two writes to 
> two tables.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/wtsi-npg/npg_qc/pull/70#issuecomment-72828331>.
>


-- 
Jaime M. Tovar Corona
Senior Software Developer
Sequence Informatics
Wellcome Trust Sanger Institute
Wellcome Trust Genome Campus
Hinxton
Cambridge UK
CB10 1SA

Email: jmtc@sanger.ac.uk
Tel:   +44 (0)1223 834244 ext.8306




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by jenniferliddle** [comment]
On 04/02/15 10:14, jmtcsngr wrote:
> Having one table saves time to insert, but is may be more expensive in
> the select. In the entity we can hit the table using the primary keys to
> get data. If we want to do a select to get the last historic we will
> need an extra index for timestamp or iscurrent, otherwise it will get
> progressively slower as the table grows.

This is true in theory. In practice we have plenty of experience to show
that adding an 'iscurrent' index does not appreciably slow down database
access.

>
> Also it allows less work when maintaining the tables. For example you
> can dump big chunks of old history to free space without worrying about
> altering what is in the entity table.

Ummm...we don't want to delete data or destroy history. Space isn't
going to be an issue.

> Because I think we will be selecting to display data more often than
> inserting I think it may be worth to use two tables. What you think?

My feeling is that the data duplication and increased complexity of the
software is more of a Bad Thing than the possibly slight increase in
access speed is a good thing. We tend to spend a lot more time
maintaining code than we do writing it, so anything that makes code
simpler and easier to maintain is worth doing.



-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Pull request merged**
