### PR TITLE
Changes to bring back collapser

### PR DESCRIPTION
**Pull request by jmtcsngr**

### CODE REVIEW

**Comment by mgcam** [comment]
Tested on MAC, Firefox 38.52. event object is not defined in callbacks for the click function. None of the collapsers works. OK in Chrome Version 50.0.2661.102 on teh same machine. The same issue in Firefox on Linux.

When this problem is resolved, the feature has to be tested on Windows (Firefox)

**Comment by mgcam** [comment]
'Collapse All' on a page with 1500 breaks the page in Chrome.  We will not try to fix this.

**Comment by jmtcsngr** [comment]
Working with:
- Linux + Chromium (49.0.2623.108) and Firefox (46.0)
- Windows Srvr 2003 + Firefox (46.0.1)

**Comment by mgcam** [comment]
Now works for a page with 384 plexes on Mac Firefox and is fast! Also works for 1500 plexes.

**Pull request merged**
